# Generated by Django 4.0.4 on 2025-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='full_name',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
